using System.Text.Json.Serialization;

public class Employee
{
    public int Id { get; set; }

    // Auto-generated by backend
    public string? EmployeeNumber { get; set; }

    [JsonPropertyName("lastName")]
    public string LastName { get; set; } = null!;

    [JsonPropertyName("firstName")]
    public string FirstName { get; set; } = null!;

    [JsonPropertyName("middleName")]
    public string? MiddleName { get; set; }

    [JsonPropertyName("dateOfBirth")]
    public DateTime DateOfBirth { get; set; }

    [JsonPropertyName("dailyRate")]
    public decimal DailyRate { get; set; }

    [JsonPropertyName("workingDays")]
    public string WorkingDays { get; set; } = null!;
}